version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./apps/converter/Dockerfile
    restart: always
    container_name: myApp
    networks:
      - myNetwork
    ports:
      - 3001:80  

  converter:
    build:
      context: .
      dockerfile: ./apps/converter/Dockerfile
    restart: always
    container_name: myConverter
    volumes:
      - ./.env:/opt/app.env
    networks:
      - myNetwork
    depends_on:
      - rmq 

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    container_name: myApi
    volumes:
      - ./.env:/opt/app.env
    networks:
      - myNetwork
    ports:
      - 3002:3000  
    depends_on:
      - rmq  

  rmq:
    image: rabbitmq:3.9.13-management
    container_name: myRmq
    restart: always
    networks:
      - myNetwork  
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

networks:
  myNetwork:
    driver: bridge
